# 服务器配置
server:
  servlet:
    context-path: /sb_mybatis
# 数据源配置
spring:
  profiles:
    active: dev
# mybatis配置
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.hejj.bean
  configuration:
    # 驼峰命名
    map-underscore-to-camel-case: true
# 分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
